/*
 * linux/arch/arm/mach-exynos/gpio-mx2.c
 *
 * Copyright (C) 2012 Meizu Technology Co.Ltd, Zhuhai, China
 * Author: 	lvcha qiu	<lvcha@meizu.com>
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2.  This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#include <asm/mach-types.h>

#include <mach/map.h>
#include <mach/gpio-common.h>
#include <mach/gpio-m040.h>

/* this table only for m040 board */
static const struct gpio_slp_info m040_slp_table[] = {
	{ "EXYNOS4_GPA0(6)",	EXYNOS4_GPA0(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*TOUCHPAD_SDA*/
	{ "EXYNOS4_GPA0(7)",	EXYNOS4_GPA0(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*TOUCHPAD_SCL*/

	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_NOISE*/
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_NOISE*/
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_ISP*/
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_ISP*/
	{"EXYNOS4_GPB(4)",	EXYNOS4_GPB(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(5)",	EXYNOS4_GPB(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(6)",	EXYNOS4_GPB(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(7)",	EXYNOS4_GPB(7), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	
	{"EXYNOS4_GPY0(4)",	EXYNOS4_GPY0(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM PMU RESET*/
	
	{"EXYNOS4_GPY1(3)",	EXYNOS4_GPY1(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	
	{"EXYNOS4_GPY2(0)",	EXYNOS4_GPY2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY2(2)",	EXYNOS4_GPY2(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM SLAVE WAKEUP*/
	{"EXYNOS4_GPY2(3)",	EXYNOS4_GPY2(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM ON1*/
	{"EXYNOS4_GPY2(4)",	EXYNOS4_GPY2(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPY3(7)",	EXYNOS4_GPY3(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPY6(0)",	EXYNOS4_GPY6(0),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM IPC TRIGIN*/
	{"EXYNOS4_GPY6(4)",	EXYNOS4_GPY6(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},  /*MODEM BB RESET*/
};

/* this table only for m041 board */
static const struct gpio_slp_info m041_slp_table[] = {
	{ "EXYNOS4_GPA0(6)",	EXYNOS4_GPA0(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*M041 TD CTS*/
	{ "EXYNOS4_GPA0(7)",	EXYNOS4_GPA0(7),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*M041 TD RTS*/

#ifdef CONFIG_MX2_SC8803G_TEST
	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*MODEM SPI_CLK*/
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*MODEM SPI_CS*/
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, 	GPIO_PULL_DOWN},/*MODEM SPI_MISO*/
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*MODEM SPI_MOSI*/
#else
	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_NOISE*/
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_NOISE*/
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_ISP*/
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_ISP*/
#endif
	{"EXYNOS4_GPB(4)",	EXYNOS4_GPB(4), 	GPIO_SLP_PREV,  GPIO_PULL_NONE},/*MODEM SPI_CLK*/
	{"EXYNOS4_GPB(5)",	EXYNOS4_GPB(5), 	GPIO_SLP_PREV,  GPIO_PULL_NONE},/*MODEM SPI_CS*/
	{"EXYNOS4_GPB(6)",	EXYNOS4_GPB(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*MODEM SPI_MISO*/
	{"EXYNOS4_GPB(7)",	EXYNOS4_GPB(7), 	GPIO_SLP_PREV,  GPIO_PULL_NONE},/*MODEM SPI_MOSI*/
	
	{"EXYNOS4_GPY0(4)",	EXYNOS4_GPY0(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*M041 AP READY*/
	
	{"EXYNOS4_GPY1(3)",	EXYNOS4_GPY1(3), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*M041 AP TO MDM2*/
	
	{"EXYNOS4_GPY2(0)",	EXYNOS4_GPY2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 MDM TO AP1*/
	{"EXYNOS4_GPY2(2)",	EXYNOS4_GPY2(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*M041 AP RTS*/
	{"EXYNOS4_GPY2(3)",	EXYNOS4_GPY2(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*M041 AP POWER ON*/
	{"EXYNOS4_GPY2(4)",	EXYNOS4_GPY2(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 TOUCHPAD SCL*/

	{"EXYNOS4_GPY3(7)",	EXYNOS4_GPY3(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 TOUCHPAD SDA*/

	{"EXYNOS4_GPY6(0)",	EXYNOS4_GPY6(0),	GPIO_SLP_PREV,	GPIO_PULL_NONE}, /*M041 AP RESEND REQUEST*/
	{"EXYNOS4_GPY6(4)",	EXYNOS4_GPY6(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},  /*M041 AP TO MDM1*/
};

/* this table for mx2 board */
static const struct gpio_slp_info mx2_slp_table[] = {
	{ "EXYNOS4_GPA0(0)",	EXYNOS4_GPA0(0),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*BT RXD*/
	{ "EXYNOS4_GPA0(1)",	EXYNOS4_GPA0(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*BT TXD*/
	{ "EXYNOS4_GPA0(2)",	EXYNOS4_GPA0(2),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*BT CTS*/
	{ "EXYNOS4_GPA0(3)",	EXYNOS4_GPA0(3),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*BT RTS*/
	{ "EXYNOS4_GPA0(4)",	EXYNOS4_GPA0(4),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*WCDMA_RXD*/
	{ "EXYNOS4_GPA0(5)",	EXYNOS4_GPA0(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WCDMA_TXD*/
	{ "EXYNOS4_GPA0(6)",	EXYNOS4_GPA0(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*TOUCHPAD_SDA*//*M041 TD CTS*/
	{ "EXYNOS4_GPA0(7)",	EXYNOS4_GPA0(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*TOUCHPAD_SCL*//*M041 TD RTS*/

	{"EXYNOS4_GPA1(0)",	EXYNOS4_GPA1(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*GPSRXD*/
	{"EXYNOS4_GPA1(1)",	EXYNOS4_GPA1(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*GPSTXD*/
	{"EXYNOS4_GPA1(2)",	EXYNOS4_GPA1(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*GPS CTS*/
	{"EXYNOS4_GPA1(3)",	EXYNOS4_GPA1(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*GPS RTS*/
	{"EXYNOS4_GPA1(4)",	EXYNOS4_GPA1(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*RXDPR*/
	{"EXYNOS4_GPA1(5)",	EXYNOS4_GPA1(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*TXDPR*/

	{"EXYNOS4_GPB(0)",	EXYNOS4_GPB(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_NOISE*/
	{"EXYNOS4_GPB(1)",	EXYNOS4_GPB(1), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_NOISE*/
	{"EXYNOS4_GPB(2)",	EXYNOS4_GPB(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_ISP*/
	{"EXYNOS4_GPB(3)",	EXYNOS4_GPB(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_ISP*/
	{"EXYNOS4_GPB(4)",	EXYNOS4_GPB(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(5)",	EXYNOS4_GPB(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(6)",	EXYNOS4_GPB(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPB(7)",	EXYNOS4_GPB(7), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/

	{"EXYNOS4_GPC0(0)",	EXYNOS4_GPC0(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*PCMAP CLK*/
	{"EXYNOS4_GPC0(1)",	EXYNOS4_GPC0(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPC0(2)",	EXYNOS4_GPC0(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*PCMAP LRC*/
	{"EXYNOS4_GPC0(3)",	EXYNOS4_GPC0(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*PCMAP RX*/
	{"EXYNOS4_GPC0(4)",	EXYNOS4_GPC0(4), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*PCMAP TX*/

	{"EXYNOS4_GPC1(0)",	EXYNOS4_GPC1(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*S/PDIF OUT*/
	{"EXYNOS4_GPC1(1)",	EXYNOS4_GPC1(1), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*TOUCH RST*/
	{"EXYNOS4_GPC1(2)",	EXYNOS4_GPC1(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SPDIF EN*/
	{"EXYNOS4_GPC1(3)",	EXYNOS4_GPC1(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_LCD_BL*/
	{"EXYNOS4_GPC1(4)",	EXYNOS4_GPC1(4), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_LCD_BL*/

	{"EXYNOS4_GPD0(0)",	EXYNOS4_GPD0(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPD0(1)",	EXYNOS4_GPD0(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*MOTO PWM*/
	{"EXYNOS4_GPD0(2)",	EXYNOS4_GPD0(2), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_TOUCH*/
	{"EXYNOS4_GPD0(3)",	EXYNOS4_GPD0(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_TOUCH*/

	{"EXYNOS4_GPD1(0)",	EXYNOS4_GPD1(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SDA_AUDIO*/
	{"EXYNOS4_GPD1(1)",	EXYNOS4_GPD1(1), 	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SCL_AUDIO*/
	{"EXYNOS4_GPD1(2)",	EXYNOS4_GPD1(2), 	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*SDA_PMIC*/
	{"EXYNOS4_GPD1(3)",	EXYNOS4_GPD1(3), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*SCL_PMIC*/

	{"EXYNOS4_GPF0(0)",	EXYNOS4_GPF0(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*WM8958 LDO1 EN*/
	{"EXYNOS4_GPF0(1)",	EXYNOS4_GPF0(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*BT WAKE*/
	{"EXYNOS4_GPF0(2)",	EXYNOS4_GPF0(2), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPF0(3)",	EXYNOS4_GPF0(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*BT RESET*/
	{"EXYNOS4_GPF0(4)",	EXYNOS4_GPF0(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF0(5)",	EXYNOS4_GPF0(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPF0(6)",	EXYNOS4_GPF0(6), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*CAMERA ISP RST*/
	{"EXYNOS4_GPF0(7)",	EXYNOS4_GPF0(7), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*WM8958 LDO2 EN*/

	{"EXYNOS4_GPF1(0)",	EXYNOS4_GPF1(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF1(1)",	EXYNOS4_GPF1(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF1(2)",	EXYNOS4_GPF1(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*WL ON*/
	{"EXYNOS4_GPF1(3)",	EXYNOS4_GPF1(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*CAMERA ISP PWRDN*/
	{"EXYNOS4_GPF1(4)",	EXYNOS4_GPF1(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF1(5)",	EXYNOS4_GPF1(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF1(6)",	EXYNOS4_GPF1(6), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*GPS PWRON*/
	{"EXYNOS4_GPF1(7)",	EXYNOS4_GPF1(7), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*NOISE ES305B WAKE*/

	{"EXYNOS4_GPF2(0)",	EXYNOS4_GPF2(0), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*NOISE ES305B RESET*/
	{"EXYNOS4_GPF2(1)",	EXYNOS4_GPF2(1), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*GS SCL*/
	{"EXYNOS4_GPF2(2)",	EXYNOS4_GPF2(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*GPS RESET*/
	{"EXYNOS4_GPF2(3)",	EXYNOS4_GPF2(3), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*CAMERA ISP INT*/
	{"EXYNOS4_GPF2(4)",	EXYNOS4_GPF2(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF2(5)",	EXYNOS4_GPF2(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF2(6)",	EXYNOS4_GPF2(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF2(7)",	EXYNOS4_GPF2(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/

	{"EXYNOS4_GPF3(0)",	EXYNOS4_GPF3(0), 	GPIO_SLP_INPUT, GPIO_PULL_NONE},/*GS SDA*/
	{"EXYNOS4_GPF3(1)",	EXYNOS4_GPF3(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF3(2)",	EXYNOS4_GPF3(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*SENSER POWER EN*/
	{"EXYNOS4_GPF3(3)",	EXYNOS4_GPF3(3), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF3(4)",	EXYNOS4_GPF3(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4_GPF3(5)",	EXYNOS4_GPF3(5), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*BT POWER ON*/

	{"EXYNOS4212_GPJ0(0)",	EXYNOS4212_GPJ0(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(1)",	EXYNOS4212_GPJ0(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(2)",	EXYNOS4212_GPJ0(2), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(3)",	EXYNOS4212_GPJ0(3), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(4)",	EXYNOS4212_GPJ0(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(5)",	EXYNOS4212_GPJ0(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(6)",	EXYNOS4212_GPJ0(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ0(7)",	EXYNOS4212_GPJ0(7), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},

	{"EXYNOS4212_GPJ1(0)",	EXYNOS4212_GPJ1(0), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*HDMI 1.0 EN*/
	{"EXYNOS4212_GPJ1(1)",	EXYNOS4212_GPJ1(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ1(2)",	EXYNOS4212_GPJ1(2), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4212_GPJ1(3)",	EXYNOS4212_GPJ1(3), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*XCLKIN*/
	{"EXYNOS4212_GPJ1(4)",	EXYNOS4212_GPJ1(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},

	{"EXYNOS4_GPK0(0)",	EXYNOS4_GPK0(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NCLK*/
	{"EXYNOS4_GPK0(1)",	EXYNOS4_GPK0(1), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NCMD*/
	{"EXYNOS4_GPK0(2)",	EXYNOS4_GPK0(2), 	GPIO_SLP_PREV, 	GPIO_PULL_NONE},/*INAND EN*/
	{"EXYNOS4_GPK0(3)",	EXYNOS4_GPK0(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND0*/
	{"EXYNOS4_GPK0(4)",	EXYNOS4_GPK0(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND1*/
	{"EXYNOS4_GPK0(5)",	EXYNOS4_GPK0(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND2*/
	{"EXYNOS4_GPK0(6)",	EXYNOS4_GPK0(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND3*/

	{"EXYNOS4_GPK1(0)",	EXYNOS4_GPK1(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(1)",	EXYNOS4_GPK1(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(2)",	EXYNOS4_GPK1(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK1(3)",	EXYNOS4_GPK1(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND4*/
	{"EXYNOS4_GPK1(4)",	EXYNOS4_GPK1(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND5*/
	{"EXYNOS4_GPK1(5)",	EXYNOS4_GPK1(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND6*/
	{"EXYNOS4_GPK1(6)",	EXYNOS4_GPK1(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*ND7*/

	{"EXYNOS4_GPK2(0)",	EXYNOS4_GPK2(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(1)",	EXYNOS4_GPK2(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(2)",	EXYNOS4_GPK2(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(3)",	EXYNOS4_GPK2(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(4)",	EXYNOS4_GPK2(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(5)",	EXYNOS4_GPK2(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPK2(6)",	EXYNOS4_GPK2(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPK3(0)",	EXYNOS4_GPK3(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*WL CLK*/
	{"EXYNOS4_GPK3(1)",	EXYNOS4_GPK3(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},/*WL CMD*/
	{"EXYNOS4_GPK3(2)",	EXYNOS4_GPK3(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL CS*/
	{"EXYNOS4_GPK3(3)",	EXYNOS4_GPK3(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL D0*/
	{"EXYNOS4_GPK3(4)",	EXYNOS4_GPK3(4), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL D1*/
	{"EXYNOS4_GPK3(5)",	EXYNOS4_GPK3(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL D2*/
	{"EXYNOS4_GPK3(6)",	EXYNOS4_GPK3(6), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*WL D3*/

	{"EXYNOS4_GPL0(0)",	EXYNOS4_GPL0(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(1)",	EXYNOS4_GPL0(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},//VERSION AA0
	{"EXYNOS4_GPL0(2)",	EXYNOS4_GPL0(2), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(3)",	EXYNOS4_GPL0(3), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(4)",	EXYNOS4_GPL0(4), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(5)",	EXYNOS4_GPL0(5), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL0(6)",	EXYNOS4_GPL0(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},//VERSION AA1

	{"EXYNOS4_GPL1(0)",	EXYNOS4_GPL1(0), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL1(1)",	EXYNOS4_GPL1(1), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},

	{"EXYNOS4_GPL2(0)",	EXYNOS4_GPL2(0), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED1*/
	{"EXYNOS4_GPL2(1)",	EXYNOS4_GPL2(1), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED2*/
	{"EXYNOS4_GPL2(2)",	EXYNOS4_GPL2(2), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED3 FACTORY TEST GPIO*/
	{"EXYNOS4_GPL2(3)",	EXYNOS4_GPL2(3), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED4*/
	{"EXYNOS4_GPL2(4)",	EXYNOS4_GPL2(4), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED5*/
	{"EXYNOS4_GPL2(5)",	EXYNOS4_GPL2(5), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LED6*/
	{"EXYNOS4_GPL2(6)",	EXYNOS4_GPL2(6), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},
	{"EXYNOS4_GPL2(7)",	EXYNOS4_GPL2(7), 	GPIO_SLP_INPUT, GPIO_PULL_DOWN},

	{"EXYNOS4212_GPM0(0)",	EXYNOS4212_GPM0(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(1)",	EXYNOS4212_GPM0(1),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*DVFS SET2*/
	{"EXYNOS4212_GPM0(2)",	EXYNOS4212_GPM0(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*DVFS SET3*/
	{"EXYNOS4212_GPM0(3)",	EXYNOS4212_GPM0(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*SET2*/
	{"EXYNOS4212_GPM0(4)",	EXYNOS4212_GPM0(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(5)",	EXYNOS4212_GPM0(5),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*DVFS SET1*/
	{"EXYNOS4212_GPM0(6)",	EXYNOS4212_GPM0(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM0(7)",	EXYNOS4212_GPM0(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4212_GPM1(0)",	EXYNOS4212_GPM1(0),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/* SET1*/
	{"EXYNOS4212_GPM1(1)",	EXYNOS4212_GPM1(1),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/* IR_SCL*/
	{"EXYNOS4212_GPM1(2)",	EXYNOS4212_GPM1(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM1(3)",	EXYNOS4212_GPM1(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM1(4)",	EXYNOS4212_GPM1(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*SET3*/
	{"EXYNOS4212_GPM1(5)",	EXYNOS4212_GPM1(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM1(6)",	EXYNOS4212_GPM1(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/

	{"EXYNOS4212_GPM2(0)",	EXYNOS4212_GPM2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(1)",	EXYNOS4212_GPM2(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(2)",	EXYNOS4212_GPM2(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(3)",	EXYNOS4212_GPM2(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4212_GPM2(4)",	EXYNOS4212_GPM2(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4212_GPM3(0)",	EXYNOS4212_GPM3(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM3(1)",	EXYNOS4212_GPM3(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM3(2)",	EXYNOS4212_GPM3(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*CAMERA F2.8V EN*/
	{"EXYNOS4212_GPM3(3)",	EXYNOS4212_GPM3(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MHL1.2V EN*/
	{"EXYNOS4212_GPM3(4)",	EXYNOS4212_GPM3(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM3(5)",	EXYNOS4212_GPM3(5),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCDN 5.5V EN*/
	{"EXYNOS4212_GPM3(6)",	EXYNOS4212_GPM3(6),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCD BL EN*/
	{"EXYNOS4212_GPM3(7)",	EXYNOS4212_GPM3(7),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*NC*/

	{"EXYNOS4212_GPM4(0)",	EXYNOS4212_GPM4(0),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*IR_SDA*/
	{"EXYNOS4212_GPM4(1)",	EXYNOS4212_GPM4(1),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*GPS1.8V EN*/
	{"EXYNOS4212_GPM4(2)",	EXYNOS4212_GPM4(2),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*MICD_SCL*/
	{"EXYNOS4212_GPM4(3)",	EXYNOS4212_GPM4(3),	GPIO_SLP_INPUT,	GPIO_PULL_UP},/*MICD_SDA*/
	{"EXYNOS4212_GPM4(4)",	EXYNOS4212_GPM4(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCD 5.5V EN*/
	{"EXYNOS4212_GPM4(5)",	EXYNOS4212_GPM4(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*NC*/
	{"EXYNOS4212_GPM4(6)",	EXYNOS4212_GPM4(6),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCD 2.8V EN*/
	{"EXYNOS4212_GPM4(7)",	EXYNOS4212_GPM4(7),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*LCD RESET*/

	{"EXYNOS4_GPY0(0)",	EXYNOS4_GPY0(0), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(1)",	EXYNOS4_GPY0(1), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(2)",	EXYNOS4_GPY0(2), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*WIFI CS*/
	{"EXYNOS4_GPY0(3)",	EXYNOS4_GPY0(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY0(4)",	EXYNOS4_GPY0(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM PMU RESET*//*M041 AP READY*/
	{"EXYNOS4_GPY0(5)",	EXYNOS4_GPY0(5), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},

	{"EXYNOS4_GPY1(0)",	EXYNOS4_GPY1(0), 	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*KEYOFF PMIC2*/
	{"EXYNOS4_GPY1(1)",	EXYNOS4_GPY1(1), 	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*CHG_SCL*/
	{"EXYNOS4_GPY1(2)",	EXYNOS4_GPY1(2), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY1(3)",	EXYNOS4_GPY1(3), 	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 AP TO MDM2*/

	{"EXYNOS4_GPY2(0)",	EXYNOS4_GPY2(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 MDM TO AP1*/
	{"EXYNOS4_GPY2(1)",	EXYNOS4_GPY2(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY2(2)",	EXYNOS4_GPY2(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM SLAVE WAKEUP*//*M041 AP RTS*/
	{"EXYNOS4_GPY2(3)",	EXYNOS4_GPY2(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM ON1*//*M041 AP POWER ON*/
	{"EXYNOS4_GPY2(4)",	EXYNOS4_GPY2(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 TOUCHPAD SCL*/
	{"EXYNOS4_GPY2(5)",	EXYNOS4_GPY2(5),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*GY_SDA*/

	{"EXYNOS4_GPY3(0)",	EXYNOS4_GPY3(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY3(1)",	EXYNOS4_GPY3(1),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*COM_SDA*/
	{"EXYNOS4_GPY3(2)",	EXYNOS4_GPY3(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY3(3)",	EXYNOS4_GPY3(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*USB SELECT*/
	{"EXYNOS4_GPY3(4)",	EXYNOS4_GPY3(4),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY3(5)",	EXYNOS4_GPY3(5),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*GY_SCL*/
	{"EXYNOS4_GPY3(6)",	EXYNOS4_GPY3(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY3(7)",	EXYNOS4_GPY3(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*M041 TOUCHPAD SDA*/

	{"EXYNOS4_GPY4(0)",	EXYNOS4_GPY4(0),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*HDMI_SCL*/
	{"EXYNOS4_GPY4(1)",	EXYNOS4_GPY4(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY4(2)",	EXYNOS4_GPY4(2),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*MHL_SCL*/
	{"EXYNOS4_GPY4(3)",	EXYNOS4_GPY4(3),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MHL WAKE*/
	{"EXYNOS4_GPY4(4)",	EXYNOS4_GPY4(4),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*TORCH EN*/
	{"EXYNOS4_GPY4(5)",	EXYNOS4_GPY4(5),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MHL RST*/
	{"EXYNOS4_GPY4(6)",	EXYNOS4_GPY4(6),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*MHL_SDA*/
	{"EXYNOS4_GPY4(7)",	EXYNOS4_GPY4(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*HDMI_SDA*/

	{"EXYNOS4_GPY5(0)",	EXYNOS4_GPY5(0),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(1)",	EXYNOS4_GPY5(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(2)",	EXYNOS4_GPY5(2),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*TOUCH PAD INT0*/
	{"EXYNOS4_GPY5(3)",	EXYNOS4_GPY5(3),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(4)",	EXYNOS4_GPY5(4),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*COM_SCL*/
	{"EXYNOS4_GPY5(5)",	EXYNOS4_GPY5(5),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*CHG_SDA*/
	{"EXYNOS4_GPY5(6)",	EXYNOS4_GPY5(6),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY5(7)",	EXYNOS4_GPY5(7),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},/*DOCK I/O*/

	{"EXYNOS4_GPY6(0)",	EXYNOS4_GPY6(0),	GPIO_SLP_PREV,	GPIO_PULL_NONE},/*MODEM IPC TRIGIN*/ /*M041 AP RESEND*/
	{"EXYNOS4_GPY6(1)",	EXYNOS4_GPY6(1),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY6(2)",	EXYNOS4_GPY6(2),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY6(3)",	EXYNOS4_GPY6(3),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*FU_SCL*/
	{"EXYNOS4_GPY6(4)",	EXYNOS4_GPY6(4),	GPIO_SLP_PREV,	GPIO_PULL_UP},  /*MODEM BB RESET*/
	{"EXYNOS4_GPY6(5)",	EXYNOS4_GPY6(5),	GPIO_SLP_INPUT,	GPIO_PULL_DOWN},
	{"EXYNOS4_GPY6(6)",	EXYNOS4_GPY6(6),	GPIO_SLP_PREV,	GPIO_PULL_UP},/*TOUCH PAD RESET*/
	{"EXYNOS4_GPY6(7)",	EXYNOS4_GPY6(7),	GPIO_SLP_INPUT,	GPIO_PULL_NONE},/*FU_SDA*/
};

static const struct gpio_info_table __initdata m040_gpio_table[] = {
	{EXYNOS4_GPA0(6), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCHPAD_SDA*/
	{EXYNOS4_GPA0(7), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCHPAD_SCL*/

	{EXYNOS4_GPY0(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM PMU RESET*/
	
	{EXYNOS4_GPY1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCH PAD SDA(VER1)*/

	{EXYNOS4_GPY2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCH PAD SCL(VER1)*/
	{EXYNOS4_GPY2(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM SLAVE WAKEUP*/
	{EXYNOS4_GPY2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM ON1*/
	{EXYNOS4_GPY2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},

	{EXYNOS4_GPY3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},
	
	{EXYNOS4_GPY6(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM IPC TRIGIN*/
	{EXYNOS4_GPY6(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM BB RESET*/
	
	{EXYNOS4_GPX1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC TRIGOUT*/
	{EXYNOS4_GPX1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC SRDY*/

	{EXYNOS4_GPX2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC HOST WAKE*/
	{EXYNOS4_GPX3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*BB RESET MONITOR*/
	{EXYNOS4_GPX3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN,		GPIO_DRVSTR_LV1},
};

static const struct gpio_info_table __initdata m041_gpio_table[] = {
	{EXYNOS4_GPA0(6), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 TD MODEM CTS*/
	{EXYNOS4_GPA0(7), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 TD MODEM RTS*/
	
	{EXYNOS4_GPY0(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP READY*/
	
	{EXYNOS4_GPY1(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP TO MDM2*/

	{EXYNOS4_GPY2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 MDM TO AP1*/
	{EXYNOS4_GPY2(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP RTS*/
	{EXYNOS4_GPY2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP POWER ON*/
	{EXYNOS4_GPY2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 TOUCHPAD SCL*/

	{EXYNOS4_GPY3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 TOUCHPAD SDA*/
	
	{EXYNOS4_GPY6(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP RESEND*/
	{EXYNOS4_GPY6(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*M041 AP TO MDM1*/

	{EXYNOS4_GPX1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 Modem RESEND*/
	{EXYNOS4_GPX1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 Modem RDY*/

	{EXYNOS4_GPX2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 Modem RTS*/
	{EXYNOS4_GPX3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 Modem Alive*/
	{EXYNOS4_GPX3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP,		GPIO_DRVSTR_LV1},/*M041 MDM TP AP2*/
};

static const struct gpio_info_table __initdata mx2_gpio_table[] = {
	{EXYNOS4_GPA0(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT RXD*/
	{EXYNOS4_GPA0(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT TXD*/
	{EXYNOS4_GPA0(2), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT CTS*/
	{EXYNOS4_GPA0(3), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT RTS*/
	{EXYNOS4_GPA0(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WCDMA_RXD*/
	{EXYNOS4_GPA0(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WCDMA_TXD*/
	{EXYNOS4_GPA0(6), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*TOUCHPAD_SDA*//*M041 TD_CTS*/
	{EXYNOS4_GPA0(7), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*TOUCHPAD_SCL*//*M041 TD_RTS*/

	{EXYNOS4_GPA1(0), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*GPSRXD*/
	{EXYNOS4_GPA1(1), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*GPSTXD*/
	{EXYNOS4_GPA1(2), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP,		GPIO_DRVSTR_LV1},/*GPS CTS*/
	{EXYNOS4_GPA1(3), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP,      	GPIO_DRVSTR_LV1},/*GPS RTS*/
	{EXYNOS4_GPA1(4), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*RXDPR*/
	{EXYNOS4_GPA1(5), 	S3C_GPIO_RESERVED, 	GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TXDPR*/

	{EXYNOS4_GPB(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_NOISE*/
	{EXYNOS4_GPB(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_NOISE*/
	{EXYNOS4_GPB(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_ISP*/
	{EXYNOS4_GPB(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_ISP*/
	{EXYNOS4_GPB(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPB(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPB(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPB(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPC0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_CLK*/
	{EXYNOS4_GPC0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPC0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_LRC*/
	{EXYNOS4_GPC0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_TX*/
	{EXYNOS4_GPC0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*PCMAP_RX*/

	{EXYNOS4_GPC1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV2},/*S/PDIF OUT*/
	{EXYNOS4_GPC1(1), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*TOUCH RST*/
	{EXYNOS4_GPC1(2), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SPDIF EN*/
	{EXYNOS4_GPC1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_LCD_BL*/
	{EXYNOS4_GPC1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_LCD_BL*/

	{EXYNOS4_GPD0(0), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPD0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*MOTO PWM*/
	{EXYNOS4_GPD0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_TOUCH*/
	{EXYNOS4_GPD0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_TOUCH*/

	{EXYNOS4_GPD1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_CODEC*/
	{EXYNOS4_GPD1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_CODEC*/
	{EXYNOS4_GPD1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SDA_PMIC*/
	{EXYNOS4_GPD1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL_PMIC*/

	{EXYNOS4_GPF0(0), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WM8958 LDO1 EN*/
	{EXYNOS4_GPF0(1), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT WAKE*/
	{EXYNOS4_GPF0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*TE*/
	{EXYNOS4_GPF0(3), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT RESET*/
	{EXYNOS4_GPF0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF0(5), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*AUDIO2.8V EN*/
	{EXYNOS4_GPF0(6), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA ISP RST*/
	{EXYNOS4_GPF0(7), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WM8958 LDO2 EN*/

	{EXYNOS4_GPF1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_HI, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF1(2), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WL ON*/
	{EXYNOS4_GPF1(3), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA ISP YCVZ EN*/
	{EXYNOS4_GPF1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF1(6), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*GPS PWRND*/
	{EXYNOS4_GPF1(7), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*NOISE ES305B WAKE*/

	{EXYNOS4_GPF2(0), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*NOISE ES305B RESET*/
	{EXYNOS4_GPF2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GS SCL*/
	{EXYNOS4_GPF2(2), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 		GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GPS RESET*/
	{EXYNOS4_GPF2(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA ISP INT*/
	{EXYNOS4_GPF2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF2(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF2(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF2(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPF3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GS SDA*/
	{EXYNOS4_GPF3(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF3(2), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SENSER POWER EN*/
	{EXYNOS4_GPF3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF3(4), 	S3C_GPIO_INPUT, 		GPIO_PULL_DOWN, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPF3(5), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BT POWER ON*/

	{EXYNOS4212_GPJ1(0), 	S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HDMI 1.0 EN*/
	{EXYNOS4212_GPJ1(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPJ1(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPJ1(3), 	S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 		GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*XCLKIN*/
	{EXYNOS4212_GPJ1(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 		GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPK0(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 		GPIO_DRVSTR_LV1},/*NCLK*/
	{EXYNOS4_GPK0(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*NCMD*/
	{EXYNOS4_GPK0(2), 	S3C_GPIO_OUTPUT,	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*iNAND EN*/
	{EXYNOS4_GPK0(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND0*/
	{EXYNOS4_GPK0(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND1*/
	{EXYNOS4_GPK0(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND2*/
	{EXYNOS4_GPK0(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND3*/

	{EXYNOS4_GPK0(0), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 		GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(1), 	S3C_GPIO_INPUT, 	GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 		GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 		GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPK1(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND4*/
	{EXYNOS4_GPK1(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND5*/
	{EXYNOS4_GPK1(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND6*/
	{EXYNOS4_GPK1(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*ND7*/

	{EXYNOS4_GPK2(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SCLK*/
	{EXYNOS4_GPK2(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SCMD*/
	{EXYNOS4_GPK2(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SCS*/
	{EXYNOS4_GPK2(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SD0*/
	{EXYNOS4_GPK2(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SD1*/
	{EXYNOS4_GPK2(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*SD2*/
	{EXYNOS4_GPK2(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE,		GPIO_DRVSTR_LV1},/*SD3*/

	{EXYNOS4_GPK3(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSDCLK*/
	{EXYNOS4_GPK3(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSCMD*/
	{EXYNOS4_GPK3(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSD_CD*/
	{EXYNOS4_GPK3(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSD0*/
	{EXYNOS4_GPK3(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSD1*/
	{EXYNOS4_GPK3(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSD2*/
	{EXYNOS4_GPK3(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*WSD3*/

	{EXYNOS4_GPL0(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},//VERSION AA0
	{EXYNOS4_GPL0(2), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(3), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(4), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(5), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL0(6), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},//VERSION AA1

	{EXYNOS4_GPL1(0), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL1(1), 	S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPL2(0), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED1*/
	{EXYNOS4_GPL2(1), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED2*/
	{EXYNOS4_GPL2(2), 	S3C_GPIO_INPUT,			GPIO_SETPIN_NONE, 	GPIO_PULL_UP,		GPIO_DRVSTR_LV1},/*LED3 FACTORY TEST GPIO*/
	{EXYNOS4_GPL2(3), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED4*/
	{EXYNOS4_GPL2(4), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED5*/
	{EXYNOS4_GPL2(5), 	S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LED6*/
	{EXYNOS4_GPL2(6), 	S3C_GPIO_INPUT,			GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPL2(7), 	S3C_GPIO_INPUT,			GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4212_GPM0(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/**/
	{EXYNOS4212_GPM0(1), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS2*/
	{EXYNOS4212_GPM0(2), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS3*/
	{EXYNOS4212_GPM0(3), S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SET2*/
	{EXYNOS4212_GPM0(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM0(5), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DVS1*/
	{EXYNOS4212_GPM0(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM0(7), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4212_GPM1(0), S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/* SET1*/
	{EXYNOS4212_GPM1(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/* IR_SCL*/
	{EXYNOS4212_GPM1(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM1(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*FRONT CAMERA STROBE*/
	{EXYNOS4212_GPM1(4), S3C_GPIO_OUTPUT,		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SET3*/
	{EXYNOS4212_GPM1(5), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM1(6), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4212_GPM2(0), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HP GAIN(TI CODEC)*/
	{EXYNOS4212_GPM2(1), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HP EN(TI CODEC)*/
	{EXYNOS4212_GPM2(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SCL MFUAL*/
	{EXYNOS4212_GPM2(3), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/* FRONT CAMREA PWDN */
	{EXYNOS4212_GPM2(4), S3C_GPIO_OUTPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*CODEC RESET(TI CODEC)*/

	{EXYNOS4212_GPM3(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM3(1), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM3(2), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA F2.8V EN*/
	{EXYNOS4212_GPM3(3), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MHL1.2V EN*/
	{EXYNOS4212_GPM3(4), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4212_GPM3(5), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCDN 5.5V EN*/
	{EXYNOS4212_GPM3(6), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCD BL EN*/
	{EXYNOS4212_GPM3(7), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/* FRONT CAMERA SHUTDOWN */

	{EXYNOS4212_GPM4(0), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IR_SDA*/
	{EXYNOS4212_GPM4(1), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ISP 1.2V EN*/
	{EXYNOS4212_GPM4(2), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA VGA SCL*/
	{EXYNOS4212_GPM4(3), S3C_GPIO_INPUT,		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*CAMERA VGA SDA*/
	{EXYNOS4212_GPM4(4), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCD 5.5V EN*/
	{EXYNOS4212_GPM4(5), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*FRONT CAMERA FIN*/
	{EXYNOS4212_GPM4(6), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCD 2.8V EN*/
	{EXYNOS4212_GPM4(7), S3C_GPIO_OUTPUT,		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*LCD RESET*/

	{EXYNOS4_GPY0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY0(2), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*WIFI CS*/
	{EXYNOS4_GPY0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY0(4), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MODEM PMU RESET*//*AP READY*/
	{EXYNOS4_GPY0(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},

	{EXYNOS4_GPY1(0), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*KEYOFF PMIC2*/
	{EXYNOS4_GPY1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*CHG_SCL*/
	{EXYNOS4_GPY1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCH PAD SDA*/

	{EXYNOS4_GPY2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCH PAD SCL*/
	{EXYNOS4_GPY2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY2(2), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM SLAVE WAKEUP*//*AP RTS*/
	{EXYNOS4_GPY2(3), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM ON1*//*AP POWER ON*/
	{EXYNOS4_GPY2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 TOUCHPAD SCL*/
	{EXYNOS4_GPY2(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GY_SDA*/

	{EXYNOS4_GPY3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY3(1), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*COM_SDA*/
	{EXYNOS4_GPY3(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY3(3), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*USB SELECT*/
	{EXYNOS4_GPY3(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY3(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GY_SCL*/
	{EXYNOS4_GPY3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*M041 TOUCHPAD SDA*/

	{EXYNOS4_GPY4(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*HDMI_SCL*/
	{EXYNOS4_GPY4(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*CHG_DETECT*/
	{EXYNOS4_GPY4(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*MHL_SCL*/
	{EXYNOS4_GPY4(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*MHL WAKE*/
	{EXYNOS4_GPY4(4), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*TORCH EN*/
	{EXYNOS4_GPY4(5), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MHL RST*/
	{EXYNOS4_GPY4(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*MHL_SDA*/
	{EXYNOS4_GPY4(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*HDMI_SDA*/

	{EXYNOS4_GPY5(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY5(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY5(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*TOUCH PAD INT0*/
	{EXYNOS4_GPY5(3), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY5(4), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*COM_SCL*/
	{EXYNOS4_GPY5(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*CHG_SDA*/
	{EXYNOS4_GPY5(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY5(7), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*DOCK I/O*/

	{EXYNOS4_GPY6(0), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM IPC TRIGIN*/ /*AP RESEND*/
	{EXYNOS4_GPY6(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY6(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY6(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*FU_SCL*/
	{EXYNOS4_GPY6(4), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_HI, 		GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*MODEM BB RESET*/
	{EXYNOS4_GPY6(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},
	{EXYNOS4_GPY6(6), 	S3C_GPIO_OUTPUT, 	GPIO_SETPIN_LOW, 	GPIO_PULL_NONE, 		GPIO_DRVSTR_LV1},/*TOUCH PAD RESET*/
	{EXYNOS4_GPY6(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*FU_SDA*/

	{EXYNOS4_GPZ(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISBCLK*/
	{EXYNOS4_GPZ(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISMCLK*/
	{EXYNOS4_GPZ(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IISWS*/
	{EXYNOS4_GPZ(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IIS_IN*/
	{EXYNOS4_GPZ(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*IIS_OUT*/
	{EXYNOS4_GPZ(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/
	{EXYNOS4_GPZ(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*NULL*/

	{EXYNOS4_GPX0(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*KEY OFF*/
	{EXYNOS4_GPX0(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCH*/
	{EXYNOS4_GPX0(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*USB VBUS*/
	{EXYNOS4_GPX0(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*SUB PMIC */
	{EXYNOS4_GPX0(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*MAIN PMIC*/
	{EXYNOS4_GPX0(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IR INT*/
	{EXYNOS4_GPX0(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*KEY_HOME */
	{EXYNOS4_GPX0(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*CODEC*/

	{EXYNOS4_GPX1(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*TOUCHPAD INT*/
	{EXYNOS4_GPX1(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*SUB PMIC  RESET*/
	{EXYNOS4_GPX1(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*BL SENSOR OUT*/
	{EXYNOS4_GPX1(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GS INT1*/
	{EXYNOS4_GPX1(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*WL HOST WAKE*/
	{EXYNOS4_GPX1(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC TRIGOUT*//*Modem RESEND*/
	{EXYNOS4_GPX1(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC SRDY*//*Modem RDY*/
	{EXYNOS4_GPX1(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 	GPIO_DRVSTR_LV1},/*HD DETEC*/

	{EXYNOS4_GPX2(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GS INT2*/
	{EXYNOS4_GPX2(1), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN, 	GPIO_DRVSTR_LV1},/*BT HOST WAKE*/
	{EXYNOS4_GPX2(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*USB ID*/
	{EXYNOS4_GPX2(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*GY DATA INT*/
	{EXYNOS4_GPX2(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC HOST WAKE*//*Modem RTS*/
	{EXYNOS4_GPX2(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*VOL+*/
	{EXYNOS4_GPX2(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*DOCK DETECT*/
	{EXYNOS4_GPX2(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*MHL INT*/

	{EXYNOS4_GPX3(0), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*LOW BAT*/
	{EXYNOS4_GPX3(1), 	S3C_GPIO_OUTPUT, 		GPIO_SETPIN_HI, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*ST2*/
	{EXYNOS4_GPX3(2), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*VOL -*/
	{EXYNOS4_GPX3(3), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*BB RESET MONITOR*//*Modem Alive*/
	{EXYNOS4_GPX3(4), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*FUG INT*/
	{EXYNOS4_GPX3(5), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_UP, 		GPIO_DRVSTR_LV1},/*IPC WAKEUP*/
	{EXYNOS4_GPX3(6), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_DOWN,		GPIO_DRVSTR_LV1},
	{EXYNOS4_GPX3(7), 	S3C_GPIO_INPUT, 		GPIO_SETPIN_NONE, 	GPIO_PULL_NONE, 	GPIO_DRVSTR_LV1},/*HDMI HPD1.8V*/
};

static void mx2_config_runtime_slp_gpio(void)
{
	 /*WIFI control pin*/
	if(gpio_get_value(M040_WL_POWER)) {
		/*BT*/
		mx_set_sleep_pin(M040_BT_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(M040_BT_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on

		/*WIFI*/
		mx_set_sleep_pin(M040_WL_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(M040_WL_WIFICS, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1

		mx_set_sleep_pin(EXYNOS4_GPK3(0), GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);// SDIO CLK
		mx_set_sleep_pin(EXYNOS4_GPK3(1), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO CMD
		mx_set_sleep_pin(EXYNOS4_GPK3(2), S3C_GPIO_INPUT, GPIO_PULL_DOWN);// SDIO CD
		mx_set_sleep_pin(EXYNOS4_GPK3(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D0
		mx_set_sleep_pin(EXYNOS4_GPK3(4), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D1
		mx_set_sleep_pin(EXYNOS4_GPK3(5), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D2
		mx_set_sleep_pin(EXYNOS4_GPK3(6), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);// SDIO D3
	}
	/* bluetooth control pin*/
	if(gpio_get_value(M040_BT_RESET)) {
		/*WIFI*/
		mx_set_sleep_pin(M040_WL_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi power pin; normal 1
		mx_set_sleep_pin(M040_WL_WIFICS, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//wifi cd pin; normal 1
		/*BT*/
		mx_set_sleep_pin(M040_BT_POWER, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_POWER 0: off; 1:on
		mx_set_sleep_pin(M040_BT_RESET, GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_RESET 0: off; 1:on
		mx_set_sleep_pin(M040_BT_WAKE, GPIO_SLP_OUT0, S3C_GPIO_PULL_NONE);//BT_WAKE 0: off; 1:on

		mx_set_sleep_pin(EXYNOS4_GPA0(0), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_RXD
		mx_set_sleep_pin(EXYNOS4_GPA0(1), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);// BT_UART_TXD
		mx_set_sleep_pin(EXYNOS4_GPA0(2), GPIO_SLP_PREV, S3C_GPIO_PULL_NONE);//BT_UART_CTS
		mx_set_sleep_pin(EXYNOS4_GPA0(3), GPIO_SLP_OUT1, S3C_GPIO_PULL_NONE);//BT_UART_RTS
	}
}
static void mx2_config_sleep_gpio(void)
{
	struct gpio_slp_info gpio;
	unsigned int i;

 	for (i = 0; i < ARRAY_SIZE(mx2_slp_table); i++) {
		gpio = mx2_slp_table[i];
		mx_set_sleep_pin(gpio.pin, gpio.type, gpio.pull);
	}
	/*platform special sleep config*/
#ifdef CONFIG_MACH_M040
	if(machine_is_m040()){
	 	for (i = 0; i < ARRAY_SIZE(m040_slp_table); i++) {
			gpio = m040_slp_table[i];
			mx_set_sleep_pin(gpio.pin, gpio.type, gpio.pull);
		}
	}
#endif
#ifdef CONFIG_MACH_M041
	if(machine_is_m041()){
	 	for (i = 0; i < ARRAY_SIZE(m041_slp_table); i++) {
			gpio = m041_slp_table[i];
			mx_set_sleep_pin(gpio.pin, gpio.type, gpio.pull);
		}
	}
#endif
	/* runtime pin config */
	mx2_config_runtime_slp_gpio();
}

static int  __init mx2_init_gpio(void)
{
	exynos4_sleep_gpio_set = mx2_config_sleep_gpio;

	mx_config_gpio_table(mx2_gpio_table, ARRAY_SIZE(mx2_gpio_table));
#ifdef CONFIG_MACH_M040
	if(machine_is_m040()){
		mx_config_gpio_table(m040_gpio_table, ARRAY_SIZE(m040_gpio_table));
	}
#endif
#ifdef CONFIG_MACH_M041
	if(machine_is_m041()){
		mx_config_gpio_table(m041_gpio_table, ARRAY_SIZE(m041_gpio_table));
	}
#endif
	return 0;
}

/* must be initialize gpio before init_machine function */
arch_initcall(mx2_init_gpio);

